Repository projectceladon/vendor-hardware-interfaces, pull requests merged in 2024-09, with the labels that each got.

#174 Mem leak evs app
  evs/apps/default/src/VideoTex.cpp
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#173 coverity fix for external camera hal
  camera/device/default/ExternalCameraDeviceSession.cpp
  camera/device/default/ExternalCameraOfflineSession.cpp
  camera/device/default/RemoteCameraDeviceSession.cpp
  camera/provider/default/ExternalCameraProvider.cpp
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#175 [WR] appear surround view camera only in reverse gear
  evs/apps/default/res/config.json
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#176 Do not use std::move since it leads to null pointer dereference
  thermal/aidl/default/Thermal.cpp
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#177 coverity fixes for external camera and remote camera
  camera/device/default/ExternalCameraDeviceSession.cpp
  camera/device/default/ExternalCameraOfflineSession.cpp
  camera/device/default/RemoteCameraDeviceSession.cpp
  camera/provider/default/ExternalCameraProvider.cpp
Labels: Valid commit message, PR approved, Developer Approved, Integration Approved, Engineering Build Successful

#162 Add the screen cast binary so and APK
  screencast/Android.bp
  screencast/DmBackendApp.apk
  screencast/ScreenCastClient.apk
  screencast/acrn-bkend-server
  screencast/dm-backend
  screencast/libCastFrontClientJni.so
  screencast/libacrn_dm_backend.so
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Not Started

#179 Fixing uninitialized variable coverity issue
  bluetooth/bluetooth_hci.cc
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#184 Update the signed screen cast apk
  screencast/DmBackendApp.apk
  screencast/ScreenCastClient.apk
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful

#185 Updated License Changes
  LICENSE
Labels: Invalid commit message, Pending Developer Approval, Engineering Build Not Started, Pending PR Review

#186 Remove widevine feature and move to innersourse
  widevine/Android.bp
  widevine/android.hardware.drm-service.widevine
  widevine/android.hardware.drm-service.widevine.rc
  widevine/libwvaidl.so
  widevine/manifest_android.hardware.drm-service.widevine.xml
  widevine/move_widevine_data.sh
Labels: Valid commit message, PR approved, Developer Approved, Engineering Build Successful
